"""`market_is_open()` and the poller agree on when a session is.

The bounds exist twice and cannot be shared: `poll.py::MARKET_OPEN` and
`MARKET_CLOSE` are Python `time` objects the poller compares against its own
clock, and `views.py::MARKET_IS_OPEN_DDL` is SQL a view evaluates. Neither
can import the other.

So the guarantee is this test. Without it the pair drifts silently, and the
failure it produces is the one that prompted the function: a price presented
as live by a view whose clock disagrees with the process that wrote it.
"""

from __future__ import annotations

import re

from capitalscan.jobs.poll import MARKET_CLOSE, MARKET_OPEN
from capitalscan.jobs.views import MARKET_IS_OPEN_DDL


def _sql_times() -> list[str]:
    """Every `TIME 'HH:MM'` literal in the function body, in order."""
    return re.findall(r"TIME '(\d{2}:\d{2})'", MARKET_IS_OPEN_DDL)


def test_the_sql_bounds_are_the_pollers_bounds():
    """The open and the regular close are the poller's, exactly.

    Asserted as membership rather than as the whole list: since
    `d2f6b48e1a07` there is a third literal, 13:00, for early closes. What
    must not drift is the pair the poller also uses to decide whether to
    poll at all.
    """
    times = _sql_times()
    assert MARKET_OPEN.strftime("%H:%M") in times
    assert MARKET_CLOSE.strftime("%H:%M") in times
    # Exactly three: open, early close, regular close. A fourth means
    # someone added a bound without saying what it is.
    assert sorted(set(times)) == ["09:30", "13:00", "16:00"]


def test_the_function_reads_eastern_time():
    """Not `now()::time`, which is the server's zone.

    ADR 127 is the cautionary case: a naive read of an ET wall clock stored
    four hours off. This machine runs on Pacific, so a missing `AT TIME
    ZONE` here would open the session at 06:30 local and close it at 13:00
    -- plausible-looking numbers that are wrong by three hours.
    """
    # Every clock read is converted, not a fixed number of them. Counting
    # occurrences broke the moment the early-close lookup added a third
    # read; the property that matters is that none is left in the server's
    # zone.
    assert MARKET_IS_OPEN_DDL.count("now()") == MARKET_IS_OPEN_DDL.count(
        "AT TIME ZONE 'America/New_York'"
    )
    assert MARKET_IS_OPEN_DDL.count("now()") >= 3


def test_early_closes_come_from_the_calendar_not_a_literal_list():
    """Half-days close at 13:00 ET, and the function looks them up.

    `trading_days.is_early_close` has existed since the reference-tables
    migration and `jobs/ingest.py` populates it from measured session
    length. The first version of this function ignored it and the code
    comment claimed no such calendar existed -- so a live price showed for
    three hours after trading ended on those days.

    Asserted as a lookup rather than a hardcoded date set: a list of
    half-days written here would need editing every year, and the calendar
    is already regenerated by `cscan calendar`.
    """
    assert "trading_days" in MARKET_IS_OPEN_DDL
    assert "is_early_close" in MARKET_IS_OPEN_DDL
    assert re.search(r"TIME '13:00'", MARKET_IS_OPEN_DDL)


def test_both_closing_times_are_present_and_ordered():
    """13:00 is the early close and 16:00 the regular one, not the reverse."""
    early = MARKET_IS_OPEN_DDL.index("13:00")
    regular = MARKET_IS_OPEN_DDL.index("16:00")
    assert early < regular, "the CASE returns the early close first"


def test_the_close_is_exclusive_and_the_open_is_not():
    """16:00:00 exactly is closed; 09:30:00 exactly is open.

    The poller uses `MARKET_OPEN <= now <= MARKET_CLOSE`, inclusive at both
    ends, so it may write one tick at 16:00:00.000. The view is `>= open`
    and `< close`, which drops that tick from the live price and keeps it in
    the candle. That is the intended asymmetry: a bar may contain the
    closing print, and a price labelled live may not outlast the session.
    """
    assert ">=" in MARKET_IS_OPEN_DDL
    # The comparison is now against a CASE, so the exclusivity lives on the
    # `<` before it rather than directly against a literal.
    assert re.search(r"::time\s*<\s*CASE", MARKET_IS_OPEN_DDL, re.S)


def test_the_function_is_stable_not_volatile():
    """`STABLE` lets Postgres evaluate it once per statement.

    `VOLATILE` would re-evaluate per row, so a screener query spanning
    16:00:00 could show some rows a live price and others none, from one
    scan of one table.
    """
    assert "STABLE" in MARKET_IS_OPEN_DDL


def test_the_view_guards_the_live_price_with_it():
    """The function existing is not the point; the view using it is."""
    from capitalscan.jobs.views import V_SCREEN_LIVE_DDL

    assert "market_is_open()" in V_SCREEN_LIVE_DDL
    # The timestamp survives. A reader who wants to know when the last tick
    # landed still can; what goes away is the number pretending to be now.
    assert "lq.ts AS live_price_ts" in V_SCREEN_LIVE_DDL
